[project]
name = "auto-booking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lin", email = "tanguanlin908@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.2.3",
    "robotframework>=7.4.2",
    "robotframework-browser>=20.4.0",
    "robotframework-browser-recorder>=0.7.0",
]

[project.scripts]
auto-booking = "auto_booking:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
